name: Deploy Website to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to Host
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: travelmap.page.gd/htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          watch.ps1
          travel_memory_map_local.sql
          create_admin.php
          dashboard_rendered.html
          app/controllers/dashboard_debug.txt
          app/controllers/login_debug.txt
          config/db_config.php
